version: "3"
services:
  redis:
    image: redis:5.0.7
  postgres:
    image: postgres:11.5
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec passenger start
    volumes:
      - .:/app
      - /app/tmp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.development
#   sidekiq:
#     build: .
#     command: bundle exec sidekiq -C config/sidekiq.yml
#     volumes:
#       - .:/app
#       - /app/tmp
#     env_file:
#       - .env.development
#     depends_on:
#       - postgres
#       - redis
